### ISSUE TITLE
Cancel button in edit is not working, questions page

### ISSUE THREAD

**Issue by paminus-kingori** [PaymasterMax/devcodes#8]

**Comment by paminus-kingori** [comment]
- [ ] cancel buttons

- [ ] adding the svg images

**Comment by PaymasterMax** [comment]
briefly describe the problem

**Comment by PaymasterMax** [comment]
i still don't have the updates,

**Comment by paminus-kingori** [comment]
did you merge?

**Comment by PaymasterMax** [comment]
i cant see anything to merge and still i cant figure out the changes, cnt see them on the main branch, after pulling from your branch;
